### ISSUE TITLE
Support for pypi options in Conda-Store via specification or other means

### ISSUE THREAD

**Issue by costrouc** [Quansight/conda-store#294]
See https://stackoverflow.com/questions/65383467/can-conda-be-configured-to-use-a-private-pypi-repo where index url can be specified in the arguments.

For example

```yaml
name: asdf
dependencies:
 - numpy
 - pip:
   - --index-url https://.../../
   - flask
```
