### ISSUE TITLE
Add documentation describing how to install pip packages from VCS, or make a reference that points to PEP440

### ISSUE THREAD

**Issue by peytondmurray** [Quansight/conda-store#325]
See https://github.com/Quansight/qhub/issues/1305 for background discussion. Due to inconsistencies in the ways that python packages can be specified to be installed in `pip` and `conda`, it would be  useful to have documentation pointing users to reference PEP440, and explaining that pip can install packages in `conda-store` as long as they follow the format:

```yaml
# environment.yaml
name: test-env
dependencies:
- numpy
- scipy
- pip
- pip:
  - tqdm @ git+https://github.com/tqdm/tqdm@master
  - <other package name> @ <other VCS repo>@<branch or commit>
```
