### ISSUE TITLE
Environment Variables parsed away

### ISSUE THREAD

**Issue by StefanBrand** [Quansight/conda-store#413]
I tried to specify `variables` key as described in Conda docs: [Setting environment variables](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#setting-environment-variables):

> Further, you can declare environment variables in the environment.yml file as shown here:

```
name: env-name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - codecov
variables:
  VAR1: valueA
  VAR2: valueB
```
After submission the new build does not include the `variables`. Activating an environment built in this way does not set environment variables.
