### ISSUE TITLE
Store references build to artifats in database

### ISSUE THREAD

**Issue by costrouc** [Quansight/conda-store#49]
E.g. create Table artifacts

```yaml
artifact:
    id: int
    type: enum.Enum (build artifact type)
    key: string
    sha256: string
    build_id: int
```

This would be required for garbage collection of builds.
