### ISSUE TITLE
linuxbrew store [enhancement]

### ISSUE THREAD

**Issue by brl0** [Quansight/conda-store#59]
Copied from https://github.com/Quansight/qhub/issues/310:

> Conda-store provides a great solution for serving environments to jupyterlab instances.
> Linuxbrew is a user level package manager that stores files in /home/linuxbrew.
> I was thinking it would be useful to be able to serve up Linuxbrew packages centrally similar to conda-store.
> I am not sure if something like this could be integrated directly into conda-store, or if a separate tool should be created for this.
> 
> Any thoughts, ideas, or suggestions would be appreciated.

**Comment by costrouc** [comment]
Thanks @brl0! I thought about this in relation to https://github.com/Quansight/conda-store/issues/58. I could image supporting multiple packaging systems in the `environment.yaml` file. Here is a rough example of what I was envisioning:

```
name: my-environment
dependencies:
  - pip
  - pip:
    - flask
  - brew
  - brew:
     - htop
  - nodejs
  - nodejs:
     - mathjs
```
